# Generated by Django 4.1.6 on 2023-02-20 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.FloatField()),
                ('product_no', models.BigIntegerField()),
                ('product_category', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=500)),
                ('product_stock', models.BigIntegerField()),
                ('product_images', models.ImageField(upload_to='products/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.seller')),
            ],
        ),
    ]
